// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:market_connect/src/core/data/models/category_model.dart';
import 'package:market_connect/src/core/data/models/debt_model.dart';
import 'package:market_connect/src/core/data/models/farmer_model.dart';
import 'package:market_connect/src/core/data/models/product_model.dart';
import 'package:market_connect/src/core/data/models/repayment_model.dart';
import 'package:market_connect/src/core/data/models/sync_queue_entry_model.dart';
import 'package:market_connect/src/core/data/models/transaction_item_model.dart';
import 'package:market_connect/src/core/data/models/transaction_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryModelAdapter());
    registerAdapter(DebtModelAdapter());
    registerAdapter(FarmerModelAdapter());
    registerAdapter(ProductModelAdapter());
    registerAdapter(RepaymentModelAdapter());
    registerAdapter(SyncQueueEntryModelAdapter());
    registerAdapter(TransactionItemModelAdapter());
    registerAdapter(TransactionModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryModelAdapter());
    registerAdapter(DebtModelAdapter());
    registerAdapter(FarmerModelAdapter());
    registerAdapter(ProductModelAdapter());
    registerAdapter(RepaymentModelAdapter());
    registerAdapter(SyncQueueEntryModelAdapter());
    registerAdapter(TransactionItemModelAdapter());
    registerAdapter(TransactionModelAdapter());
  }
}
